### ISSUE TITLE
Changing competition id broken

### ISSUE THREAD

**Issue by Harry-R** [skylines-project/skylines#696]
After changing the competition ID of an already uploaded flight, the ID in at the overview pannel is changed, but the one at the barogram panel is not. 

![skylines_compid_bug](https://user-images.githubusercontent.com/7561362/31449967-89610a8e-aea8-11e7-8801-7bcf5bdde73b.png)

**Comment by Harry-R** [comment]
Seems to be a caching problem, after cleaning the browser cache it works properly. Nevertheless it is confusing and should be fixed.

**Comment by lordfolken** [comment]
**Needs current reproduction** (2026 revitalization triage)

Still reproducible after login?

Please reply with a fresh repro on the current site. We may close this issue if there is no reply.

**Comment by lordfolken** [comment]
### Triage pointers (2026-09-18)

**Likely area:** `ember/app/components/change-aircraft-form.js` + flight page consumers of `competition_id` (e.g. `ember/app/components/plane-label-overlay.hbs`, form/sidebar tables)
**Related:** —
**Notes:** Needs current repro. Overview label updates but barogram-panel label stays stale; reporter also saw a browser-cache workaround. After POST `/api/flights/:id/`, verify whether in-memory flight / CDN-cached JSON used by the map label is refreshed.
**Hypothesis (non-binding):** Guess — save succeeds but one UI path keeps a cached `competition_id` (or relies on a cached flight payload) instead of the updated model.
